"""Kantone table

Revision ID: 59c575a138a2
Revises: 2b4cfc3e5eda
Create Date: 2023-03-12 16:25:35.489685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c575a138a2'
down_revision = '2b4cfc3e5eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kantone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('abbr', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_cn'), ['cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_organization'), ['organization'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_organization'))
        batch_op.drop_index(batch_op.f('ix_certificate_cn'))

    op.drop_table('kantone')
    # ### end Alembic commands ###
